/**/callback({
  "meta": {
    "Content-Type": "application/javascript; charset=utf-8",
    "X-RateLimit-Limit": "60",
    "X-RateLimit-Remaining": "48",
    "X-RateLimit-Reset": "1465404425",
    "Cache-Control": "public, max-age=60, s-maxage=60",
    "Vary": "Accept",
    "ETag": "\"7a9d8ca8cea7ca1a20b67c5a6eeaa8e3\"",
    "Last-Modified": "Wed, 08 Jun 2016 10:26:11 GMT",
    "X-GitHub-Media-Type": "github.v3; format=json",
    "status": 200
  },
  "data": {
    "id": 10290605,
    "name": "typed.js",
    "full_name": "mattboldt/typed.js",
    "owner": {
      "login": "mattboldt",
      "id": 1389818,
      "avatar_url": "https://avatars.githubusercontent.com/u/1389818?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mattboldt",
      "html_url": "https://github.com/mattboldt",
      "followers_url": "https://api.github.com/users/mattboldt/followers",
      "following_url": "https://api.github.com/users/mattboldt/following{/other_user}",
      "gists_url": "https://api.github.com/users/mattboldt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mattboldt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mattboldt/subscriptions",
      "organizations_url": "https://api.github.com/users/mattboldt/orgs",
      "repos_url": "https://api.github.com/users/mattboldt/repos",
      "events_url": "https://api.github.com/users/mattboldt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mattboldt/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/mattboldt/typed.js",
    "description": "A jQuery typing animation script.",
    "fork": false,
    "url": "https://api.github.com/repos/mattboldt/typed.js",
    "forks_url": "https://api.github.com/repos/mattboldt/typed.js/forks",
    "keys_url": "https://api.github.com/repos/mattboldt/typed.js/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/mattboldt/typed.js/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/mattboldt/typed.js/teams",
    "hooks_url": "https://api.github.com/repos/mattboldt/typed.js/hooks",
    "issue_events_url": "https://api.github.com/repos/mattboldt/typed.js/issues/events{/number}",
    "events_url": "https://api.github.com/repos/mattboldt/typed.js/events",
    "assignees_url": "https://api.github.com/repos/mattboldt/typed.js/assignees{/user}",
    "branches_url": "https://api.github.com/repos/mattboldt/typed.js/branches{/branch}",
    "tags_url": "https://api.github.com/repos/mattboldt/typed.js/tags",
    "blobs_url": "https://api.github.com/repos/mattboldt/typed.js/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/mattboldt/typed.js/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/mattboldt/typed.js/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/mattboldt/typed.js/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/mattboldt/typed.js/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/mattboldt/typed.js/languages",
    "stargazers_url": "https://api.github.com/repos/mattboldt/typed.js/stargazers",
    "contributors_url": "https://api.github.com/repos/mattboldt/typed.js/contributors",
    "subscribers_url": "https://api.github.com/repos/mattboldt/typed.js/subscribers",
    "subscription_url": "https://api.github.com/repos/mattboldt/typed.js/subscription",
    "commits_url": "https://api.github.com/repos/mattboldt/typed.js/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/mattboldt/typed.js/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/mattboldt/typed.js/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/mattboldt/typed.js/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/mattboldt/typed.js/contents/{+path}",
    "compare_url": "https://api.github.com/repos/mattboldt/typed.js/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/mattboldt/typed.js/merges",
    "archive_url": "https://api.github.com/repos/mattboldt/typed.js/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/mattboldt/typed.js/downloads",
    "issues_url": "https://api.github.com/repos/mattboldt/typed.js/issues{/number}",
    "pulls_url": "https://api.github.com/repos/mattboldt/typed.js/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/mattboldt/typed.js/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/mattboldt/typed.js/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/mattboldt/typed.js/labels{/name}",
    "releases_url": "https://api.github.com/repos/mattboldt/typed.js/releases{/id}",
    "deployments_url": "https://api.github.com/repos/mattboldt/typed.js/deployments",
    "created_at": "2013-05-25T22:17:44Z",
    "updated_at": "2016-06-08T10:26:11Z",
    "pushed_at": "2016-06-02T02:50:45Z",
    "git_url": "git://github.com/mattboldt/typed.js.git",
    "ssh_url": "git@github.com:mattboldt/typed.js.git",
    "clone_url": "https://github.com/mattboldt/typed.js.git",
    "svn_url": "https://github.com/mattboldt/typed.js",
    "homepage": "http://www.mattboldt.com/demos/typed-js/",
    "size": 1467,
    "stargazers_count": 2437,
    "watchers_count": 2437,
    "language": "JavaScript",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 461,
    "mirror_url": null,
    "open_issues_count": 81,
    "forks": 461,
    "open_issues": 81,
    "watchers": 2437,
    "default_branch": "master",
    "network_count": 461,
    "subscribers_count": 92
  }
})
